### ISSUE TITLE
Is trove.com's down?

### ISSUE THREAD

**Issue by kyoto7250** [Hyde46/hoard#105]
I accessed the README.md link but a 404 was returned 🤔

https://github.com/Hyde46/hoard/blob/7c3ff76180f0b8cb59a350c2cb550cfe82c9b4a6/README.md?plain=1#L171-L173

<img width="662" alt="スクリーンショット 2022-04-15 15 17 03" src="https://user-images.githubusercontent.com/50972773/163529646-91931a97-dd51-487b-90cf-751439156b43.png">

**Comment by Hyde46** [comment]
Thanks for raising this issue. Ill have to replace this link with something that is actually working.
This was just supposed to be a placeholder link. troves.com never was intended to be a webservice to offer exemplary trove files.
