### ISSUE TITLE
add Cargo.lock file to the repo

### ISSUE THREAD

**Issue by Builditluc** [Hyde46/hoard#125]
Hey!

I want to package hoard for nixpkgs and it would be nice if you could commit the Cargo.lock file.
Are there any releases planned because the last one was 6 months ago?

Thanks!

**Comment by Hyde46** [comment]
Hey @Builditluc !
Since `hoard` is a binary executable not a lib, this totally makes sense, thank you!

Yes, a new release is planned with a couple of updates and bug fixes. For the last couple of moths,  I didn't have access to my working station unfortunately.

**Comment by Hyde46** [comment]
Added the lock file
