### ISSUE TITLE
Probably doesn't work on zsh+macos

### ISSUE THREAD

**Issue by conradludgate** [Hyde46/hoard#171]
I just stumbled upon this project (I'm a maintainer of atuin and it popped up in a search I made).

I notice you have a similar shell setup and managed to get crossterm to work, something we were struggling with.

Upon further inspection, it doesn't seem like you do anything different so I actually think it _doesn't_ work for you, but only on ZSH + MacOS.

I came to this conclusion: https://github.com/ellie/atuin/pull/331#issuecomment-1246613773
sharing it here since you may also run into it at some point

**Comment by Hyde46** [comment]
Hey @conradludgate, thanks a lot for the link :) 
Atuin was a great inspiration on how to get the shell plugins for autocomplete to work. Great project!

Yeah unfortunately I did not test the mac + zsh combination when I switched from termion to crossterm. Ill probably have to switch back, now that I learn that I'm not the only one with that issue 😄
