### ISSUE TITLE
add command to print shell configs

### ISSUE THREAD

**Issue by LordMZTE** [Hyde46/hoard#186]
It'd be great to have a command like `hoard shell-config $SHELL` that could be used like `hoard shell-config fish | source` in order to ship shell configs embedded in the binary. This has the advantage of allowing shell configs to be automatically updated without the user having to do anything.

I'd like to create a PR for this :D

**Comment by Hyde46** [comment]
Sounds like a very useful addition!
I'm pretty open on the implementation details. Do you want some pointers, or happy to go on your own?

`hoard` already has other paramter flags with more than one word. They have been appended with underscores, so to keep things consistent, i'd go with `shell_config`
See [here](https://github.com/Hyde46/hoard#set-parameter-token)

**Comment by LordMZTE** [comment]
Yea, one more question: the current shell configs hard-code the keybind to Ctrl-h. Maybe we should add a CLI option that omits the command that sets the keybind, so the user can add that themselves. Thoughts?
