### ISSUE TITLE
Use struct arguments

### ISSUE THREAD

**Issue by LordMZTE** [Hyde46/hoard#189]
The `clap` crate somewhat recently got the ability to declare command-line arguments as a struct as opposed to the current yaml solution. If we used this feature, we could could clean up the current code, as instead of something like `sub_m.value_of("arg")`, getting an argument would be as simple as accessing a struct field: `sub_m.arg`. This also increases performance, as there will no longer be a need to parse the yaml file declaring the arguments on every startup.

Clap got this feature in `3.0.0`, but hoard is currently still on `2.33.3`, so an upgrade would be necessary.

**Comment by Hyde46** [comment]
I have had that on my plate for some time now. It would be nice to switch. 
Thanks a lot for bringing this up, i'll prioritise it!
