### ISSUE TITLE
Ubuntu .deb packages missing from releases

### ISSUE THREAD

**Issue by ArcticSnowman** [Hyde46/hoard#213]
The install.sh assumes that a hoard DEB is available to use but that's not present in any releases.

**Comment by Hyde46** [comment]
Thanks for the info, I used to have a script to create the DEB package for each release, seems like it's not running anymore. Will fix! :)

**Comment by Hyde46** [comment]
Added amd64 deb package for the latest release. Looking into building one for `x86_64` if you need that

**Comment by ArcticSnowman** [comment]
Thanks, the package installed correctly.
