### ISSUE TITLE
Customize tab highlight color

### ISSUE THREAD

**Issue by Shirtpantswallet** [Hyde46/hoard#250]
In [render.rs](https://github.com/Hyde46/hoard/blob/main/src/gui/list_search/render.rs#L73), it looks like the tabs have a default color that is not configurable. If I were to open a PR to enable this functionality, would there be interest in it?

**Comment by Hyde46** [comment]
Sounds good!
I think the combination of `(181, 118, 20)` is covered as `config.secondary_color`
