### ISSUE TITLE
New releases not being published, causing installation errors.

### ISSUE THREAD

**Issue by jwidauer** [Hyde46/hoard#291]
It seems like the CI job for releasing new versions to crates.io is broken, causing the version to be stuck at 1.3.2, which fails to compile.
The failing release job can be seen [here](https://github.com/Hyde46/hoard/actions/runs/5707045738/job/15463350821) and the latest release on crates.io is [here](https://crates.io/crates/hoard-rs/versions).

I had a quick look and I believe you should be able to update to using [v2](https://github.com/marketplace/actions/publish-crates) of the publish crates action, which might fix the error.

**Comment by Hyde46** [comment]
Thanks for pointing it out, will fix :)
