### ISSUE TITLE
Improve Input Parameter Prompt Clarity and User-Friendliness

### ISSUE THREAD

**Issue by nazdridoy** [Hyde46/hoard#307]
Hello! I've been using hoard-rs to manage my frequently used commands, and I appreciate the convenience it offers. However, I've noticed that the current prompt for input parameters can be a bit confusing, especially when dealing with complex commands. I'd like to suggest a more user-friendly approach to prompting for parameters.

**Current Prompt Example:**
```
echo "My name is #first #named parameter! and I live at #city. ##Did! I #tell you!! my name, #first?"
Provide first parameter
   >
```
**Suggested Improved Prompt:**

```
echo "My name is #first #named parameter! and I live at #city. ##Did! I #tell you!! my name, #first?"
Provide #first
>
Provide #named parameter!
>
Provide #city
>

```
**Explanation:**
The proposed change involves asking for each parameter with its corresponding name in the prompt. This approach should make it much clearer and easier for users to understand which parameter they are being prompted for. By providing a direct reference to the parameter name, users can more accurately identify the data they need to input. This enhancement can significantly enhance the user experience and reduce confusion, particularly when dealing with complex commands.

Thank you for considering this suggestion. I believe it will improve the overall usability of hoard-rs and make it even more user-friendly for both new and experienced users.

**Additional Notes:**

1. This change could potentially improve user satisfaction and reduce the learning curve when working with the tool.
2. Providing descriptive parameter names in the prompt aligns with user expectations and is consistent with modern command-line interfaces.

**Comment by Hyde46** [comment]
Hey!
That's a great suggestion and an obvious improvement in UX :) 
Will work on this sooner than later

**Comment by Hyde46** [comment]
Apparently i never closed this, but UX is definitely improved on this. Thanks again!
