### ISSUE TITLE
Homebrew download failure (most v1.4.2 url paths contain a typo)

### ISSUE THREAD

**Issue by ethanmsl** [Hyde46/hoard#316]
Homebrew installation fails due to a bad download address.

This link gives a 404, and is used by Homebrew: 
`https://github.com/Hyde46/hoard/releases/download/v1.4.2/hoard_v1.4.2_x86_64-apple-darwin.zip` 

This link works, and comes from clicking on 'versions' in the github page:
`https://github.com/Hyde46/hoard/releases/download/v1.4.2/hoard_v.1.4.2_x86_64-apple-darwin.zip`

<img width="715" alt="hoard diff" src="https://github.com/Hyde46/hoard/assets/33399972/947fd04c-706a-4023-a6af-46c916d85e61">

---

The live addresses appear to use a `v.#.#.#` style vs a `v#.#.#` style.
(the live address style above is used for all the existing links except the `amd.deb` file)

Looking at a few past releases the current style seems to be the outlier:

## "v.1.4.2"

<img width="809" alt="hoard link styles" src="https://github.com/Hyde46/hoard/assets/33399972/625ef7fb-af33-461f-92d3-76069deb1b4e">

## "v1.4.1"
<img width="548" alt="v141 comparison" src="https://github.com/Hyde46/hoard/assets/33399972/fe71b458-6a5c-439a-8d09-3845ab39e567">

## "v1.4.0"
<img width="528" alt="v140 comparisson" src="https://github.com/Hyde46/hoard/assets/33399972/f7ce7885-f9e6-4ead-97fd-e9a095b57ccb">

---

Not especially necessary, but brew response to current install attempt:

Input:
```zsh
brew tap Hyde46/hoard
brew install hoard
```
Output:
>Error: hoard: Failed to download resource "hoard"
Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.7-16-g59cc141\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5.1\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://github.com/Hyde46/hoard/releases/download/v1.4.2/hoard_v1.4.2_x86_64-apple-darwin.zip` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404
HTTP/2 404
server: GitHub.com
...

**Comment by Hyde46** [comment]
Thanks for pointing this out! I need to be more carful with version tagging..

I fixed the release and removed the bad versioning. Using brew to install it should work again
