### ISSUE TITLE
Support more linux distros and MacOS

### ISSUE THREAD

**Issue by Hyde46** [Hyde46/hoard#33]
Add installers for
- Arch linux
- Mac OS
(-Windows?)

**Comment by dfireBird** [comment]
So PKGBUILD is a package description file, which `makepkg` uses to build the `.tar.zst` file, similar to `.deb` in Debian and `pacman` can be used to install that package using the `.tar.zst` file.

So the AUR hosts the PKGBUILD file, which people download and use it to install the package. If you want only to publish to AUR, you don't need the PKGBUILD file in the repo, but if you want provide the package (i.e the `tar.zst` file) in releases of github using github actions, it's easier to have the PKGBUILD file in the repo.

I still need to research more about on how to publish your package to AUR.

**Comment by Hyde46** [comment]
Closing for now
