### ISSUE TITLE
[Feature Request] Allow to move commands to different namespaces after creating them

### ISSUE THREAD

**Issue by FriederikeHanssen** [Hyde46/hoard#45]
If one forgets to assign the command to the proper namespace  it would be nice to do this later on from within the program

**Comment by Hyde46** [comment]
Commands should probably generally be editable. 
How about adding an edit mode in the GUI?

**Comment by Hyde46** [comment]
Simple edit mode with `hoard edit --name <command_name>` is ready with the next release ( See #46 )
