### ISSUE TITLE
Distinction of file and url based on what given when using `import` command

### ISSUE THREAD

**Issue by dfireBird** [Hyde46/hoard#51]
We could use uriparse crate or somehow parse the string into a URI and dispatch action based on the parsed object!

**Comment by dfireBird** [comment]
I was trying out the url crate (it's also in `requwest::Url` module) and I tried the sending the `parse` method three types of strings:
1. http/https url
2. Unix paths
3. Windows paths

The `parse` method returns 
1. parsed `Url` object
2. an `Error` with `ErrorType` variant `RelativePathWithoutBase`

For windows paths is where things get complicated. The windows paths gets parsed as a correct URL but with the drive letter being the scheme of URL and path being remaining path that didn't get parsed.
For example, the windows path `C:\Programming\trove.yml` gets parsed into a URL object with scheme as `C` and path as `Programming\trove.yml`.


So my proposal is to parse the string given by the user, if what they gave
1. gets parsed into correct Url object (that is with http(s) as scheme) then use get request
2. returns a `RelativePathWithoutBase` error and the OS is of type unix, then consider this as a path
3. if parsed object is with a scheme of single letter (assuming most users don't have more than 26 drives) and the OS is Windows, then consider this also a path
4. throw error, if anything other than that

**Comment by Hyde46** [comment]
Sounds great with that crate.

Regarding windows, I have not considered that OS generally for any of the functionality. I'm actually not sure if `hoard` even works in a windows terminal.

Agree with your proposal for the implementation. I'd say, go ahead!
