### ISSUE TITLE
[feature request] Add/remove/move/edit commands in TUI

### ISSUE THREAD

**Issue by FedericoStra** [Hyde46/hoard#93]
Awesome program! :rocket:
Would it be possible to allow editing the trove interactively in the TUI? I think it would be more convenient to browse the hoarded commands and edit them directly in the same interface, instead of browsing » remembering the name of a command »`hoard edit #` » browsing again.

**Comment by Hyde46** [comment]
Thanks @FedericoStra! 
Those are some good suggestions, that would greatly improve UX, I'll be working on that! 🚀

**Comment by Hyde46** [comment]
@FedericoStra Extremely late, but with 1.3 inline editing/deleting and creating will be added.
See branch `dev/1.3`

**Comment by Hyde46** [comment]
Part of [release 1.3](https://github.com/Hyde46/hoard/releases/tag/v1.3.0) now
